#theme: minima
title: IQB_NTU_symposium2026

#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

include:
  - _includes/head-custom.html
  
