#theme: minima
title: IQB_NTU_symposium2026

#remote_theme: "mmistakes/minimal-mistakes@4.26.2"
remote_theme: pages-themes/dinky@v0.2.0

url: "https://nakatolab.github.io"
baseurl: "/IQB_NTU_symposium2026"

plugins:
  - jekyll-remote-theme

include:
  - _includes/head-custom.html
  
