title: UTokyo_NTU_symposium2026
timezone: "Asia/Tokyo"

#url: "https://nakatolab.github.io"
#baseurl: "/IQB_NTU_symposium2026"
url: "https://ut-ntu-2026.iqb.u-tokyo.ac.jp"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "mint" #"contrast" # "air" "contrast" "dark" "mint" "sunrise" なども可
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

search: false

footer:
