title: IQB_NTU_symposium2026
timezone: "Asia/Tokyo"

url: "https://nakatolab.github.io"
baseurl: "/IQB_NTU_symposium2026"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "air" # "air" "contrast" "dark" "mint" "sunrise" なども可

search: false

footer:
