title: "International Symposium on XXXXX"
description: "A two-day international symposium on XXXXX."
timezone: "Asia/Tokyo"

url: "https://nakatolab.github.io"
baseurl: "/IQB_NTU_symposium2026"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
permalink: pretty

minimal_mistakes_skin: "default"   # "air" "contrast" "dark" "mint" "sunrise" なども可

search: false

logo: "/assets/images/logo.png" 

# ヘッダーナビ
navigation:
  - title: "Home"
    url: /
  - title: "Program"
    url: /schedule/
  - title: "Speakers"
    url: /speakers/
  - title: "Venue"
    url: /venue/

# フッター（任意）
footer:
  links:
    - label: "Contact"
      url: "mailto:symposium2026@example.edu"
